services:
  app:
    container_name: qr-api
    environment:
      - NAME=${NAME}
      - DESCRIPTION=${DESCRIPTION}
      - LANGUAGE=${LANGUAGE}
      - VERSION=${VERSION}
      - ADDRESS=${ADDRESS}
      - PORT=${PORT}
    tty: true
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - learning

  qr-database:
    image: postgres:11.22-alpine3.17
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 1s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge

volumes:
  postgres-db: